# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "debian/jessie64"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
    vb.customize ["modifyvm", :id, "--memory", "1024"]
  end


  $script = <<SCRIPT
    sudo apt-get update && apt-get -y install git
    git clone https://github.com/netbrain/dotfiles
    ./dotfiles/install.debian.sh
    ./dotfiles/link-dotfiles.sh
SCRIPT
  
  config.vm.provision "shell", inline: $script

end
