#!/bin/bash

# turn on go vendoring experiment
#export GO15VENDOREXPERIMENT=1
# number of cpus
#export GOMAXPROCS=1
export GOROOT=/usr/local/go
# gopath
export GOPATH=$HOME/dev/go
# go bins
export PATH=$PATH:$GOPATH/bin
export PATH=$PATH:/usr/local/go/bin
