#!/bin/bash

function color_my_prompt {
    local __user_and_host="\[\]\[\033[38;5;39m\]\u\[\]\[\033[38;5;9m\]@\[\]\[\]\[\033[38;5;208m\]\h\[\]"
    local __cur_location="\[\033[38;5;198m\]\w"
    local __git_branch_color="\[\033[32m\]"
    local __git_branch='`git branch 2> /dev/null | grep -e ^* | sed -E  s/^\\\\\*\ \(.+\)$/\(\\\\\1\)\ /`'
    local __prompt_tail="\n\[\]\[\]\[\033[38;5;243m\]\$\[\]"
    local __last_color="\[\033[00m\]"
    export PS1="$__user_and_host $__cur_location $__git_branch_color$__git_branch$__prompt_tail$__last_color "
}
color_my_prompt
